export const guitarChords = [
  {
    name: "Major 7M △",
    openStrings: [],
    firstFinger: "50",
    secondFinger: "10",
    thirdFinger: "31",
    fourthFinger: "21",
    barre: {position: "", cells: []},
    deadStrings: ["0", "4"],
  },
  { name: "Major 7m",
    openStrings: [],
    firstFinger: "",
    secondFinger: "21",
    thirdFinger: "42",
    fourthFinger: "",
    barre: {position: "0", cells: ["0", "1", "2", "3", "4", "5"]},
    deadStrings: [],
  },
  { name: "Minor 7m",
    openStrings: [],
    firstFinger: "",
    secondFinger: "",
    thirdFinger: "42",
    fourthFinger: "",
    barre: {position: "0", cells: ["0", "1", "2", "3", "4", "5"]},
    deadStrings: [],
  },
  { name: "Major 7M △",
    openStrings: [],
    firstFinger: "",
    secondFinger: "21",
    thirdFinger: "32",
    fourthFinger: "12",
    barre: {position: "0", cells: ["0", "1", "2", "3", "4"]},
    deadStrings: ["5"],
  },
  { name: "Major 7m",
    openStrings: [],
    firstFinger: "",
    secondFinger: "",
    thirdFinger: "32",
    fourthFinger: "12",
    barre: {position: "0", cells: ["0", "1", "2", "3", "4"]},
    deadStrings: ["5"],
  },
  { name: "Minor 7m",
    openStrings: [],
    firstFinger: "",
    secondFinger: "",
    thirdFinger: "32",
    fourthFinger: "11",
    barre: {position: "0", cells: ["0", "1", "2", "3", "4"]},
    deadStrings: ["5"],
  },
  { name: "Minor 7m (half diminished) Ø",
    openStrings: [],
    firstFinger: "10",
    secondFinger: "51",
    thirdFinger: "21",
    fourthFinger: "31",
    barre: {position: "", cells: []},
    deadStrings: ["0","4"],
  },
  { name: "Minor 7m (half diminished) Ø",
    openStrings: [],
    firstFinger: "40",
    secondFinger: "20",
    thirdFinger: "31",
    fourthFinger: "11",
    barre: {position: "", cells: []},
    deadStrings: ["0","5"],
  },
  { name: "Minor 6",
    openStrings: [],
    firstFinger: "11",
    secondFinger: "21",
    thirdFinger: "30",
    fourthFinger: "51",
    barre: {position: "", cells: []},
    deadStrings: ["0", "4"],
  }
];